name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Python 3.x to match the Docker setup

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs \
                      mkdocs-material \
                      mkdocs-exclude \
                      mkdocs-material-extensions \
                      mkdocs-minify-plugin \
                      mkdocs-git-authors-plugin \
                      mkdocs-git-committers-plugin \
                      mkdocs-git-revision-date-localized-plugin \
                      "mkdocs-material[imaging]" \
                      pymdown-extensions \
                      neoteroi-mkdocs \
                      pillow \
                      cairosvg
        env:
          CD: true

      - name: Build MkDocs site
        run: mkdocs build --verbose

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
